PATH=$PATH"/opt/;/opt/local/bin;/opt/local/;/opt/local/include;/opt/local/etc/"; export PATH
EDITOR="vim"; export EDITOR
LANG="ru_RU.UTF-8"; export LANG
LC_CTYPE="ru_RU.UTF-8"; export LC_CTYPE
LC_COLLATE="POSIX"; export LC_COLLATE
LC_ALL="ru_RU.UTF-8"; export LC_ALL
#export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W\[\033[m\]\$ "
ps1() {
echo -n "";
}

export CLICOLOR=1
export PS1="\[\e[32m\]\h\[\e[m\]@\[\e[33m\]:\[\e[m\]\[\e[33m\]\w\[\e[m\]\\$ "
 
